services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: fiche_flash
      POSTGRES_PASSWORD: fiche_flash
      POSTGRES_DB: fiche_flash
    ports:
      - "5432:5432"
    volumes:
      - fiche_flash_db:/var/lib/postgresql/data

volumes:
  fiche_flash_db:
